### ISSUE TITLE
urljoin() trims path

### ISSUE THREAD

**Issue by mapshen** [vladvasiliu/kibana-prometheus-exporter-py#4] opened 2020-01-28 18:04 UTC
For example, if I have `KIBANA_URL` set to `http://localhost:5601/dev`, this [line](https://github.com/vladvasiliu/kibana-prometheus-exporter-py/blob/master/kibana_prometheus_exporter/kibana_collector.py#L132) gives out `http://localhost:5601/api/status` instead of `http://localhost:5601/dev/api/status`, which causes the warning:
```
WARNING:kibana_collector:Got a HTTP error 404 while trying to contact Kibana:
404 Client Error: Not Found for url: http://localhost:5601/api/status
```

**Comment by vladvasiliu** [comment] 2020-01-29 08:47
Thanks for the report.
The issue is related to the way [`urljoin()`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin) works, apparently it expects a full path on the "base" side and a relative one on the "url" side.
See the [related commit](https://github.com/vladvasiliu/kibana-prometheus-exporter-py/commit/79a2587c61c5dad53061acfddb1700361adfc1c9) for the workaround. I've also added [some tests](https://github.com/vladvasiliu/kibana-prometheus-exporter-py/blob/1f06ea8a8070f8f45f7c09886694122d5020d5c2/test/test_url_join.py), feel free to let me know if you see any missing cases.

**Comment by mapshen** [comment] 2020-01-30 03:39
> Thanks for the report.
> The issue is related to the way [`urljoin()`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin) works, apparently it expects a full path on the "base" side and a relative one on the "url" side.
> See the [related commit](https://github.com/vladvasiliu/kibana-prometheus-exporter-py/commit/79a2587c61c5dad53061acfddb1700361adfc1c9) for the workaround. I've also added [some tests](https://github.com/vladvasiliu/kibana-prometheus-exporter-py/blob/1f06ea8a8070f8f45f7c09886694122d5020d5c2/test/test_url_join.py), feel free to let me know if you see any missing cases.

Hi @vladvasiliu thanks a bunch for the quick response and comprehensive fix! The MR looks great to me.

**Comment by vladvasiliu** [comment] 2020-01-30 07:29
I've merged this to master and bumped the version to 1.10. A docker container is being built.

**Closed by vladvasiliu** 2020-01-30 07:29 UTC
